---
title: "outlier_analiza korelacji"
author: "Krzysztof Kurek"
date: "27 02 2020"
output: html_document
---

```{r}
dane <- read.csv("../train_set.csv", stringsAsFactors = FALSE, na.strings="")
dane$X1 <- NULL

dane_numeryczne <- dane %>% 
  group_by(playlist_genre) %>% 
  select_if(is.numeric)
```
#KORELACJE
##Tabela korelacji
```{r}
korelacje_liczbowo <- round(cor(dane_numeryczne1),2); korelacje_liczbowo
```
## Modyfikacja tabeli korelacji - usunięcie wartości powyżej 1 
```{r}
upper <- korelacje_liczbowo
upper[upper.tri(korelacje_liczbowo)] <- ""
upper <- as.data.frame(upper); upper

```
## Korelacje - wykres graficzny
```{r}
library(corrplot)
library(RColorBrewer)
corrplot(korelacje_liczbowo, type = "upper", order ="hclust",
         col=brewer.pal(n=13, name ="RdYlBu"))
```

## Korelacje - wykres numeryczny
```{r}
corrplot(korelacje_liczbowo,method = "number" ,type = "upper", order ="hclust",
         col=brewer.pal(n=13, name ="RdYlBu"))
```

# OUTLIERS

```{r}
IQR(dane_numeryczne)
```

