---
title: "analiza wstepna"
author: "Krzysztof Kurek"
date: "20 02 2020"
output: html_document
---

```{r}
dane <- train_set

library(dplyr)
library(reshape2)
library(zoo)
library(lubridate)
library(ggplot2)
```

#Wstepna analiza danych
```{r}
head(dane)
```
```{r}
tail(dane)
```
```{r}
summary(dane)
```
```{r}
glimpse(dane)
```
```{r}
dim(dane)
```

# Weryfikacja wartości brakujących
```{r}
na_dane <- sapply(dane, function(y)sum(length(which(is.na(y)))))
na_dane <- as.data.frame(na_dane); na_dane
```
```{r}
dane[is.na(dane$track_name),]

```
# Weryfikacja gatunków muzycznych
```{r}
unique(dane$playlist_genre)
```
```{r}
dane%>% 
  group_by(playlist_genre) %>% 
  summarise(ilosc_utworow = n())
```
```{r}
dane%>% 
  group_by(playlist_genre) %>% 
  summarise(ilosc_utworow = n()) %>%
  arrange(desc(ilosc_utworow)) %>% 
  ggplot() + geom_col(aes(x = playlist_genre, y = ilosc_utworow)) +
  labs(title = "Rozkład ilość utworów na gatunki muzyczne",
       x = "Garunki muzyczne",
       y = "ilość utworów")

# Widzimy, że naliczniejszą grupą utworów jest grupa edm, następnie rap i pop
```
```{r}
dane$track_album_release_date <- ymd(dane$track_album_release_date)

# 1498 rekordów nie posiada odpowiedniego formatu daty

dane$track_album_release_date <- as.Date(as.yearmon(dane$track_album_release_date, "%Y%m"))

dane %>% 
  group_by(track_album_release_date, playlist_genre) %>% 
  filter(track_album_release_date >= "1963-01-01") %>% 
  summarise(ilosc_utworow = n()) %>% 
  ggplot(aes(x = track_album_release_date, y = ilosc_utworow, color = playlist_genre, fill = playlist_genre)) + geom_col()+
  scale_x_date(date_breaks = "10 year" )+
  labs(title = "Rozkład dodawanych utworów na przestrzeni lat z podziałem na gatunki",
       x = "Rok",
       y = "ilość utworów")+
  ylim(0,300)

# Do roku 1990 najczęściej dodawanym gatunkiem muzycznym był rock i , później zaczęto dodawać rap, latyno i Po
```

# Ilość dodawanych utworów w poszczególnych miesiącach
```{r}
dane$miesiac <- month(dane$track_album_release_date)

dane%>% 
  group_by(miesiac) %>% 
  summarise(ilosc_utworow = n()) %>%
  filter(!is.na(miesiac)) %>% 
  arrange(desc(ilosc_utworow)) %>% 
  ggplot() + geom_col(aes(x = miesiac, y = ilosc_utworow)) +
  labs(title = "Rozkład ilość dodawanych utworów w poszczególnych miesiącach",
       x = "miesiąc",
       y = "ilość utworów")+
  scale_x_continuous(breaks = seq(1,12,1))

```
# Tabela dodawanych utworów na przestrzeni lat z podziałem na gatunek muzyczny
```{r}
dcast(dane, track_album_release_date ~ playlist_genre )
```

