---
title: "Przyklad RMarkdown"
author: "Igor"
date: "14 02 2020"
output: github_document
always_allow_html: true
---

```{r}
library(lubridate)
library(tidyverse)
library(kableExtra)
library(ggthemes)
```

create global theme to use later

```{r}
my_theme <- theme_fivethirtyeight() + theme(axis.title = element_text(), axis.title.x = element_text())

mydata_train <- read.csv("../train_set.csv", stringsAsFactors = FALSE, na.strings="")

mydata_test <- read.csv("../test_set.csv", stringsAsFactors = FALSE, na.strings="")
```

```{r}
mydata_train %>% colnames()
```

```{r}
summarise(group_by(mydata_train, playlist_genre), srednia = mean(danceability))
```


```{r}
mydata_train %>% group_by(playlist_genre) %>% summarise(srednia = mean(danceability))
```



```{r }
mydata_train %>% 
  filter(tempo > 100)
```


union obu zbiorow
```{r}
mydata <- bind_rows(mydata_train, mydata_test)
```

```{r}
str(mydata)
```

```{r}
head(mydata, n = 20) %>% kable() %>% kable_styling()
```

```{r}
tail(mydata, n = 20)
```

```{r}
summary(mydata)
```

deleting id varaibles - no added value

```{r}
colnames(mydata)
mydata <- mydata %>% select(-track_id, -track_album_id, -playlist_id)
```

limited data - zmienna celu + zmienne wartoĹ›ciowe

```{r}
my_limited <- mydata %>% select(playlist_genre, track_popularity, danceability, energy, key, loudness, mode, acousticness, instrumentalness, liveness, valence, tempo)
```

```{r}
str(my_limited)
```

```{r}
summary(my_limited)
```

```{r}
missing_data <- mydata %>% summarise_all(~(sum(is.na(.))/n()))
missing_data <- gather(missing_data, key = "variables", value = "percent_missing")
missing_data <- missing_data[missing_data$percent_missing > 0.0, ] 
missing_data  # missing (NA) values in 3 columns
```

```{r}
ggplot(missing_data, aes(x = reorder(variables, percent_missing), y = percent_missing))  +
  geom_bar(stat = "identity", fill = "blue", size = 0.3) + xlab("Column name")
```

```{r}
mydata %>% filter(is.na(track_name))
```

1800 dates are not full dates --> change to year only

```{r}
mydata$track_album_release_date <- substr(mydata$track_album_release_date, 1, 4)
str(mydata$track_album_release_date)
```

checking number of track releases per genre over the years > 1990
```{r}
temp <- mydata %>% filter(track_album_release_date >= 1990) %>% group_by(track_album_release_date, playlist_genre) %>% summarize(album_count = n())

ggplot(temp, aes(x = track_album_release_date, y = album_count, color = playlist_genre, size = album_count)) +
  geom_point()
```

```{r}
quantile(mydata$track_popularity,seq(0,1,by=0.1))
```

variables distribution per playlist_genre

song count per genre

```{r}
temp <- mydata %>% select(playlist_genre, track_popularity) %>% group_by(playlist_genre) %>% summarise(count = n())

ggplot(temp, aes(x = playlist_genre)) + geom_bar(fill = "red")
```

popularity
```{r}
temp <- mydata %>% select(playlist_genre, track_popularity) %>% group_by(playlist_genre)

ggplot(temp, aes(track_popularity)) +
  geom_histogram(bins = 50, aes(y = ..density..), fill = "red") +  
  geom_density(alpha = 0.002, fill = "black") + 
  my_theme  + ggtitle("Distribution of popularity") +
  geom_vline(xintercept = round(mean(temp$track_popularity), 2), size = 1, linetype = 2) +
  facet_wrap(~ playlist_genre)
```

danceability

```{r}
temp <- mydata %>% select(playlist_genre, danceability) %>% group_by(playlist_genre)

ggplot(temp, aes(danceability)) +
  geom_histogram(bins = 50, aes(y = ..density..), fill = "red") +  
  geom_density(alpha = 0.002, fill = "black") + 
  my_theme  + ggtitle("Distribution of danceability") +
  geom_vline(xintercept = round(mean(temp$danceability), 2), size = 1, linetype = 2) +
  facet_wrap(~ playlist_genre)
```

energy

```{e}
temp <- mydata %>% select(playlist_genre, energy) %>% group_by(playlist_genre)

ggplot(temp, aes(energy)) +
  geom_histogram(bins = 50, aes(y = ..density..), fill = "red") +  
  geom_density(alpha = 0.002, fill = "black") + 
  my_theme  + ggtitle("Distribution of energy") +
  geom_vline(xintercept = round(mean(temp$energy), 2), size = 1, linetype = 2) +
  facet_wrap(~ playlist_genre)
```

key

```{r}
temp <- mydata %>% select(playlist_genre, key) %>% group_by(playlist_genre)

ggplot(temp, aes(key)) +
  geom_histogram(bins = 10, aes(y = ..density..), fill = "red") +  
  geom_density(alpha = 0.002, fill = "black") + 
  my_theme  + ggtitle("Distribution of key") +
  geom_vline(xintercept = round(mean(temp$key), 2), size = 1, linetype = 2) +
  facet_wrap(~ playlist_genre)
```

