---
title: "Projekt1_Bartek"
author: "Bartosz Adamiec"
date: "17 02 2020"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("fansi")
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(kableExtra)
library(ggthemes)
library(corrplot)
```


```{r}
#environment preparation and data load
my_theme <- theme_fivethirtyeight() + theme(axis.title = element_text(), axis.title.x = element_text())

mydata_train <- read.csv("../train_set.csv", stringsAsFactors = FALSE, na.strings="")

mydata_test <- read.csv("../test_set.csv", stringsAsFactors = FALSE, na.strings="")
```

```{r}
#removing useless columns(columns with id numbers, not needed in this data analysis)
mydata_train[,c("track_id", "track_album_id", "playlist_id")] <- NULL

```

```{r}
#first look at the dataframe
head(mydata_train)
#structure of df
str(mydata_train)
#dimensions
dim(mydata_train)
#more info about each collumn
summary(mydata_train)
```

```{r}
#checking nr of null values in each collumn
na_count <-sapply(mydata_train, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)
na_count

```

```{r}
#looking at rows with missing track name
mydata_train[is.na(mydata_train$track_name),]

#as we see all of the missing values are from 4 tracks
```

```{r}
#GENRES

#nr of unique genres
length(unique(mydata_train$playlist_genre))

#genre names
unique(mydata_train$playlist_genre)

#how many tracks belong to each genre
genrecount <- count(mydata_train, vars = mydata_train$playlist_genre)
genrecount

#plot
genreplot <- ggplot(genrecount) +
  geom_col(aes(x=vars, y=n, fill=vars)) +
  ggtitle("Nr of tracks in each genre") +
  xlab("Genre") +
  ylab("Nr of tracks") +
  my_theme
genreplot




```


```{r}
#SUBGENRES

#extracting genres and subgenres from df
subgenre <- data.frame(table(mydata_train$playlist_genre, mydata_train$playlist_subgenre))
colnames(subgenre) <- c("Genre","Subgenre", "n") 
subgenre <- subgenre[-which(subgenre$n == 0 ), ]

#????
genreMeans <- aggregate(. ~ Genre, subgenre[-2], mean)
for(i in 1:nrow(subgenre)) {
  for(j in 1:nrow(genreMeans)){
    if(subgenre$Genre[i] == genreMeans$Genre[j]) {
      subgenre$Means[i] = genreMeans$n[j]
    }
  }
}

#ordering data by nr of tracks in each subgenre and grouping with genres
subgenre <- subgenre[order(subgenre$n),]
subgenre$Subgenre <- factor(subgenre$Subgenre, levels = subgenre$Subgenre[order(subgenre$Genre)])


ggplot(subgenre, aes(x=Subgenre, y=n, fill=Genre)) +
  geom_bar(stat = "identity") +
  ylab("Nr of tracks") +   
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Nr of tracks in each subgenre") +
  geom_point(aes(y=Means))


#using geom point to show genre means as I couldn't find the way to do this with lines

```

```{r}
#POPULARITY
popTracks <- mydata_train %>% select(track_name, playlist_genre, playlist_subgenre, track_popularity) %>% group_by(playlist_genre)

#Most popuplar tracks
popTracks[popTracks['track_popularity'] == max(popTracks['track_popularity']),]

#Popuarity distribution with genres
ggplot(popTracks, aes(track_popularity, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(popTracks$track_popularity), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of track popularities")

#as we see there are a lot of tracks that are not popular at all
count(popTracks[popTracks['track_popularity'] <= 0.1,])
```


```{r}
#RELEASE YEAR
relYear <- mydata_train %>% select(playlist_genre, track_album_release_date) %>% group_by(playlist_genre)

#format date to year
relYear$track_album_release_date <- as.Date(relYear$track_album_release_date)
relYear$year <- format(relYear$track_album_release_date, format="%Y")
relYear <- relYear[complete.cases(relYear),]

ggplot(relYear, aes(year, fill=playlist_genre)) +
  geom_histogram(stat="count", binwidth = 50) +
  my_theme +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_discrete(breaks = c("1970", "1980", "1990", "2000", "2010", "2020")) +
  ggtitle("Nr of released tracks in each year")

#most tracks in the dataset were released after 2010
```


```{r}
#DANCEABILITY
dancea <- mydata_train %>% select(playlist_genre, track_name, track_artist, danceability) %>% group_by(playlist_genre)
#most danceable track
dancea[dancea$danceability == max(dancea$danceability),]

ggplot(dancea, aes(danceability, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(dancea$danceability), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks danceability")

#Distribution of danceability is rather normal, skewed to the left. 
```


```{r}
#ENERGY
energy <- mydata_train %>% select(playlist_genre, track_name, track_artist, energy) %>% group_by(playlist_genre)
#most energetic tracks
energy[energy$energy == max(energy$energy),]

ggplot(energy, aes(energy, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(energy$energy), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks energy")

#Distribution of energy is skewed to the left. Most tracks are rather energetic.
```


```{r}
#KEYS
keys <- mydata_train %>% select(playlist_genre, track_name, track_artist, key) %>% group_by(playlist_genre)

ggplot(keys, aes(key, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  my_theme +
  ggtitle("Distribution of tracks keys") +
  facet_wrap(~ playlist_genre)
```

```{r}
#MODE
mode <- mydata_train %>% select(playlist_genre, track_name, track_artist, mode) %>% group_by(playlist_genre)

ggplot(mode, aes(mode, fill=playlist_genre)) +
  geom_bar() +
  my_theme +
  ggtitle("Does track use mode?(N|Y)") +
  scale_x_discrete(breaks = c(0, 1)) +
  facet_wrap(~ playlist_genre) 
```


```{r}
#LOUDNESS
loud <- mydata_train %>% select(playlist_genre, track_name, track_artist, loudness) %>% group_by(playlist_genre)
#loudest/most quiet tracks
loud[loud$loudness == max(loud$loudness),]
loud[loud$loudness == min(loud$loudness),]

ggplot(loud, aes(loudness, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(loud$loudness), size = 1, linetype = 6) +
  my_theme +
  scale_x_discrete(limits = c(-30, -20, -10, 0, 5)) +
  ggtitle("Distribution of tracks loudness")

```


```{r}
#SPEECHINESS
speech <- mydata_train %>% select(playlist_genre, track_name, track_artist, speechiness) %>% group_by(playlist_genre)

speech[speech$speechiness == max(speech$speechiness),]

ggplot(speech, aes(speechiness, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(speech$speechiness), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks speechiness") +
  facet_wrap(~ playlist_genre) 

#Distribution of tracks speechiness is skewed to the right. Biggest part of tracks lacks vocal.
```

```{r}
#ACOUSTICNESS
acc <- mydata_train %>% select(playlist_genre, track_name, track_artist, acousticness) %>% group_by(playlist_genre)

acc[acc$acousticness == max(acc$acousticness),]

ggplot(acc, aes(acousticness, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(acc$acousticness), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks acousticness") +
  facet_wrap(~ playlist_genre) 
#Distribution of tracks acousticness is skewed to the right. Most tracks are not acoustic.

```


```{r}
#INSTRUMENTALNESS
ins <- mydata_train %>% select(playlist_genre, track_name, track_artist, instrumentalness) %>% group_by(playlist_genre)

ins[ins$instrumentalness == max(ins$instrumentalness),]

ggplot(ins, aes(instrumentalness, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(ins$instrumentalness), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks instrumentalness") +
  facet_wrap(~ playlist_genre) 

```

```{r}
#LIVENESS
live <- mydata_train %>% select(playlist_genre, track_name, track_artist, liveness) %>% group_by(playlist_genre)

live[live$liveness == max(live$liveness),]

ggplot(live, aes(liveness, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(live$liveness), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks liveness") +
  facet_wrap(~ playlist_genre) 
#Data is skewed to the right - most tracks were not recorded live


#kradzione od Pawła żeby zobaczyć jak wygląda
ggplot(live, aes(liveness)) +
  geom_histogram(bins = 50, aes(y = ..density..), fill = "red") +  
  geom_density(alpha = 0.002, fill = "black") + 
  my_theme  + ggtitle("Distribution of liveness") +
  geom_vline(xintercept = round(mean(live$liveness), 2), size = 1, linetype = 2) +
  facet_wrap(~ playlist_genre) +scale_x_log10()

```

```{r}
#VALENCE
vlc <- mydata_train %>% select(playlist_genre, track_name, track_artist, valence) %>% group_by(playlist_genre)

vlc[vlc$valence == max(vlc$valence),]

ggplot(vlc, aes(valence, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(vlc$valence), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks valence grouped by genre") +
  facet_wrap(~ playlist_genre) 

ggplot(vlc, aes(valence, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(vlc$valence), size = 1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks valence")

#Distribution of valence is rather normal. Most tracks sound neutral (or mixed?)
```

```{r}
#TEMPO
temp <- mydata_train %>% select(playlist_genre, track_name, track_artist, tempo) %>% group_by(playlist_genre)

temp[temp$tempo == max(temp$tempo),]

ggplot(temp, aes(tempo, fill=playlist_genre)) +
  geom_histogram(bins=25) +
  geom_density(alpha = 0.002, fill = "black") +
  geom_vline(xintercept = mean(temp$tempo), size = .1, linetype = 6) +
  my_theme +
  ggtitle("Distribution of tracks tempo") 
#Bigger part of tracks has more than 120 beats per minute

```

```{r}
#DURATION
dur <- mydata_train %>% select(playlist_genre, track_name, track_artist, duration_ms) %>% group_by(playlist_genre)

dur[dur$duration_ms == max(dur$duration_ms),]

ggplot(dur, aes(duration_ms, fill=playlist_genre)) +
  geom_histogram(bins=50) +
  geom_vline(xintercept = mean(dur$duration_ms), size = .1, linetype = 6) +
  my_theme +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Distribution of tracks duration") +
  facet_wrap(~ playlist_genre) 
#Distribution of duration is skewed to the right. Most tracks go on for 3 minutes or more.
```

